version: '3.7'
services:
  bucket-mongodb:
    container_name: bucket-mongodb
    image: mongo:4.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb
    # volumes:
    #   - ./data:/data/db

  bucket-node:
    container_name: bucket-node
    build:
      context: .
      dockerfile: docker/bucket-node/Dockerfile
    environment:
      - MONGODB_HOST=bucket-mongodb
      - API_PORT=3000
      - TESTING=true
    ports:
      - 3000:3000
    command: ['npm', 'run', 'dev']
    volumes:
      - ./src:/usr/src
